### ISSUE TITLE
Stock planning, al meter un producto específico en el wizard da traceback

### ISSUE THREAD

**Issue by anajuaristi** [odoomrp/odoomrp-utils#89]
Buenas, haciendo pruebas con el stock planning, he metido un producto en el wizard y me salta este traceback.
Gracias!

Traceback (most recent call last):
  File "/opt/odoo/demo_odoomrp/core/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/demo_odoomrp/core/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/demo_odoomrp/core/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/demo_odoomrp/core/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/demo_odoomrp/core/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/demo_odoomrp/core/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/demo_odoomrp/core/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/demo_odoomrp/core/addons/web/controllers/main.py", line 952, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/demo_odoomrp/core/addons/web/controllers/main.py", line 940, in _call_kw
    return checked_call(request.db, _args, *_kwargs)
  File "/opt/odoo/demo_odoomrp/core/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/demo_odoomrp/core/addons/web/controllers/main.py", line 939, in checked_call
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/demo_odoomrp/core/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/demo_odoomrp/core/openerp/api.py", line 363, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/demo_odoomrp/odoomrp_addons/stock_planning/wizard/wiz_stock_planning.py", line 56, in calculate_stock_planning
    cond.append(('product_id', '>', self.product_id.id))
AttributeError: 'wiz.stock.planning' object has no attribute 'product_id'

**Comment by alfredoavanzosc** [comment]
Corregido, se estaba haciendo referencia al campo "product_id" del wizard, cuando se debía de hacer referencia al campo "product".
Cierro esta issue, y continuo con la issue https://github.com/odoomrp/odoomrp-utils/issues/90
